#pragma once

typedef enum {
    HidViewSubmenu,
    HidViewVariableItemList,
    HidViewRemoteMenu,
    HidViewKeynote,
    HidViewKeyboard,
    HidViewNumpad,
    HidViewMedia,
    HidViewMusicMacOs,
    HidViewMovie,
    HidViewMouse,
    HidViewMouseClicker,
    HidViewMouseJiggler,
    HidViewMouseJigglerStealth,
    BtHidViewTikTok,
    HidViewIosPhone,
    HidViewPushToTalk,
    HidViewPushToTalkMenu,
    HidViewPushToTalkHelp,
    HidViewDialog,
    HidViewHelp,
    HidViewPopup,
    HidViewTextInput,
    HidViewFileBrowser,
} HidView;
